logging.level.org.springframework.web=DEBUG

// expose all actuator (health-check) endpoints
management.endpoints.web.exposure.include=*

spring.main.banner-mode=off

spring.datasource.url=jdbc:mysql://localhost:3306/product_service
spring.datasource.username=product_service_user1
spring.datasource.password=product_service_user1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update